package net.sue445.kulib.util;

import com.google.apphosting.api.ApiProxy;

public final class MemcacheUtil {
	private MemcacheUtil(){

	}

	/**
	 * get current version ID (auto generated by appengine)
	 * @return
	 */
	public static String getCurrentVersionId() {
		return ApiProxy.getCurrentEnvironment().getVersionId();
	}

	/**
	 * create key prefix (ex. 1.0_FooService_)
	 * @param clazz
	 * @return
	 */
	public static String createKeyPrefix(Class<?> clazz){
		return getCurrentVersionId() + "_" + clazz.getSimpleName() + "_";
	}

}
